version: '3.8'

services:
  app:
      image: node:18
      container_name: node_app
      working_dir: /usr/src/app
      volumes:
        - .:/usr/src/app
      ports:
        - "3000:3000"
      command: ["npm", "run", "start:dev"]
      env_file:
      - ./.env.development
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test
    ports:
      - "5432:5432" # O padrão do PostgreSQL é a porta 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network

volumes:
  postgres_data:
    driver: local

networks:
  postgres_network:
    driver: bridge
